unit:
  LOGMSTAR: 'log(solMass)'
  FLUX_W1: 'nanomaggy'
  FLUX_W2: 'nanomaggy'
  FLUX_W3: 'nanomaggy'
  FLUX_IVAR_W1: 'nanomaggy^-2'
  FLUX_IVAR_W2: 'nanomaggy^-2'
  FLUX_IVAR_W3: 'nanomaggy^-2'
  CIV_1549_FLUX: '10**-17 erg/(s cm2)'
  CIV_1549_FLUX_IVAR: '10**+34 (s2 cm4) / erg2'
  CIV_1549_SIGMA: 'km / s'
  MGII_2796_FLUX: '10**-17 erg/(s cm2)'
  MGII_2796_FLUX_IVAR: '10**+34 (s2 cm4) / erg2'
  MGII_2796_SIGMA: 'km / s'
  MGII_2803_FLUX: '10**-17 erg/(s cm2)'
  MGII_2803_FLUX_IVAR: '10**+34 (s2 cm4) / erg2'
  MGII_2803_SIGMA: 'km / s'
  OII_3726_FLUX: '10**-17 erg/(s cm2)'
  OII_3726_FLUX_IVAR: '10**+34 (s2 cm4) / erg2'
  OII_3726_EW: 'Angstrom'
  OII_3726_EW_IVAR: 'Angstrom^-2'
  OII_3729_FLUX: '10**-17 erg/(s cm2)'
  OII_3729_FLUX_IVAR: '10**+34 (s2 cm4) / erg2'
  OII_3729_EW: 'Angstrom'
  OII_3729_EW_IVAR: 'Angstrom^-2'
  NEV_3426_FLUX: '10**-17 erg/(s cm2)'
  NEV_3426_FLUX_IVAR: '10**+34 (s2 cm4) / erg2'
  HEII_4686_FLUX: '10**-17 erg/(s cm2)'
  HEII_4686_FLUX_IVAR: '10**+34 (s2 cm4) / erg2'
  HBETA_EW: 'Angstrom'
  HBETA_EW_IVAR: 'Angstrom^-2'
  HBETA_FLUX: '10**-17 erg/(s cm2)'
  HBETA_FLUX_IVAR: '10**+34 (s2 cm4) / erg2'
  HBETA_BROAD_FLUX: '10**-17 erg/(s cm2)'
  HBETA_BROAD_FLUX_IVAR: '10**+34 (s2 cm4) / erg2'
  HBETA_BROAD_SIGMA: 'km / s'
  HBETA_BROAD_CHI2: 'Angstrom'
  OIII_5007_FLUX: '10**-17 erg/(s cm2)'
  OIII_5007_FLUX_IVAR: '10**+34 (s2 cm4) / erg2'
  OIII_5007_SIGMA: 'km / s'
  OI_6300_FLUX: '10**-17 erg/(s cm2)'
  OI_6300_FLUX_IVAR: '10**+34 (s2 cm4) / erg2'
  HALPHA_EW: 'Angstrom'
  HALPHA_EW_IVAR: 'Angstrom^-2'
  HALPHA_FLUX: '10**-17 erg/(s cm2)'
  HALPHA_FLUX_IVAR: '10**+34 (s2 cm4) / erg2'
  HALPHA_BROAD_FLUX: '10**-17 erg/(s cm2)'
  HALPHA_BROAD_FLUX_IVAR: '10**+34 (s2 cm4) / erg2'
  HALPHA_BROAD_VSHIFT: 'km / s'
  HALPHA_BROAD_SIGMA: 'km / s'
  NII_6584_FLUX: '10**-17 erg/(s cm2)'
  NII_6584_FLUX_IVAR: '10**+34 (s2 cm4) / erg2'
  SII_6716_FLUX: '10**-17 erg/(s cm2)'
  SII_6716_FLUX_IVAR: '10**+34 (s2 cm4) / erg2'
  SII_6731_FLUX: '10**-17 erg/(s cm2)'
  SII_6731_FLUX_IVAR: '10**+34 (s2 cm4) / erg2'